DROP DATABASE IF EXISTS db1;
CREATE DATABASE db1;
USE db1;
DROP TABLE IF EXISTS table1;
CREATE TABLE table1 (
  `name` varchar(255) NOT NULL
);

DROP DATABASE IF EXISTS db2a;
CREATE DATABASE db2a;
USE db2a;
DROP TABLE IF EXISTS table1;
CREATE TABLE table1 (
  `name` varchar(255) NOT NULL
);
DROP TABLE IF EXISTS table2;
CREATE TABLE table2 (
  `name` varchar(255) NOT NULL
);

DROP DATABASE IF EXISTS db2b;
CREATE DATABASE db2b;
USE db2b;
DROP TABLE IF EXISTS table1;
CREATE TABLE table1 (
  `name` varchar(255) NOT NULL
);
DROP TABLE IF EXISTS table2;
CREATE TABLE table2 (
  `name` varchar(255) NOT NULL
);
